---
title: "ADS_22mei2019"
author: "Gerko Vink"
date: "Fundamental Techniques in Datascience with R"
output: 
   html_document:
    toc: true
    toc_depth: 5
    toc_float: true
    number_sections: true
---

<style type="text/css">

body{ /* Normal  */
      font-size: 12px;
  }
td {  /* Table  */
  font-size: 12px;
}
h1.title {
  font-size: 18px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 18px;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 18px;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>


---

Dag allen, 

Zie hieronder. 

Groet, 

Gerko

---

# Doel van de cursus

Het cursusdoel is cf. Osiris als volgt geformuleerd:


At the end of this course, students are able to:
 
1. *apply and interpret the basic methodological and statistical concepts that are associated with doing predictive and/or inferential research;*
- explain concepts from inferential statistics, such as probability, inference and modeling; and apply them in practice. 
- make an informed choice for research designs that are suitable for regression analyses.
- apply and explain the choice for techniques to investigate data problems.
- apply and explain the concepts of linearity and non-linearity.
- interpret statistical software output and report software output following APA reporting guidelines.
- explain and conceptualize statistical inference and its relation to statistical theory.
- perform the different steps in solving basic regression analysis problems and report on these steps.
 
2. *apply and interpret important techniques in linear and logistic regression analysis;*
- perform, interpret and evaluate quantitative (causal) analyses on data with the statistical software platform R.
- perform analyses in statistical software. 
 
Het doel voor ADS studenten om de benodigde kennis en tools te ontwikkelen om de volgende statistische peilers te kunnen toepassen: estimation, prediction en testing. Kennis over deze technieken bereidt de student voor op het vervolg van de minor en/of een eventuele master. Een groot deel van de meer geavanceerde technieken in data science borduurt voort op, of kent haar oorsprong in deze technieken. 

Daarnaast brengt deze cursus de studenten de basis van scripting met `R` bij.

`R`-packages die aan bod komen in de cursus; 

```{r eval = FALSE, message=FALSE}
library(magrittr)   # pipes - Bache & Wickham (2019)
library(haven)      # data import - Wickham & Miller (2018) 
library(plyr)       # data wrangling - Wickham (2011)
library(dplyr)      # data wrangling - Wickham, François, Henry & Müller (2019)
library(tidyr)      # data tidying - Wickham & Henry (2019)
library(data.table) # data management - Dowle & Srinivason (2019)
library(DT)         # interactive tables - Xie (2016)
library(ggplot2)    # visualization - Wickham (2016)
library(rmarkdown)  # Dynamic documents for R with RStudio - Allaire et al. (2019) + Xie et al. (2018)
```

---

# Opzet cursus over de weken

| Week #  | Topic   | `R`-practical | Workgroup | 
|---|---------|-----------|-----------|
| 1 | The elemental building blocks of `R` | Assigning objects and elements; creating vectors, matrices, dataframes and lists | Receive instructions and form groups |
| 2 | Finding the least squares solution; simple linear regression | Subsetting data; using pipes to simplify the workflow | Locate a data set for predictive modeling and formulate a research hypothesis; make sure that the set facilitates continuous and dichotomous outcomes |
| 3 | Linear modeling in `R`; testing assumptions; standardized residuals, leverage and Cook's distance | Class `lm` in `R`; modeling, prediction and visualization | Fit your defined model; evaluate if assumptions are met |
| 4 | Inferential modeling; Confidence intervals and hypothesis testing, non-constant error variance | Demonstrate confidence validity of the linear model on simulated data with `rmarkdown` | Test and quantify the effect of the defined model; continue the project in `rmarkdown` |
| 5 | Model evaluation; cross-validation; categorical variables, non-linear relations, interactions and higher-order polynomials | Cross-validation and model fit in `R` | Evaluate if the model can be improved; **Prepare assignment A; evaluate the final linear model on your own data** |
| 6 | Simple logistic regression | Class `glm(formula, family = "binomial")` in `R`; modeling, prediction and visualization | Fit your defined model; evaluate if assumptions are met |
| 7 | Formulating the logistic model and interpreting the parameters; marginal effects | Parameter transformations; scale of the predictor/outcome and prediction and confidence intervals | Test and quantify the effect of the defined model |
| 8 | Logistic regression model evaluation; cross-validation; multiple regression; interactions | Multiple logistic regression and cross-validating the logistic regression in `R` | Evaluate if the model can be improved; **Prepare assignment B; evaluate a logistic model on your own data** |

---

# Practicals met learnr
In plaats van de beloofde video, zie hieronder een **draft** versie van een autonoom te maken practicum met `learnr` en `shiny`. 

- [draft versie eerste practicum](https://gerkovink.shinyapps.io/FTiD_Practical_1/)

---

# References for the packages used by students

- JJ Allaire and Yihui Xie and Jonathan McPherson and Javier Luraschi and Kevin Ushey and Aron Atkins and Hadley Wickham and Joe Cheng and Winston Chang and Richard Iannone (2019). rmarkdown: Dynamic Documents for R. R package version 1.12. URL https://rmarkdown.rstudio.com.
- Matt Dowle and Arun Srinivasan (2019). data.table: Extension of `data.frame`. R package version 1.12.0. https://CRAN.R-project.org/package=data.table
- Jared E. Knowles (2019). eeptools: Convenience Functions for Education Data. R package version 1.2.2. https://CRAN.R-project.org/package=eeptools
- Stefan Milton Bache and Hadley Wickham (2014). magrittr: A Forward-Pipe Operator for R. R package version 1.5. https://CRAN.R-project.org/package=magrittr
- Hadley Wickham (2011). The Split-Apply-Combine Strategy for Data Analysis. Journal of Statistical Software, 40(1), 1-29. URL http://www.jstatsoft.org/v40/i01/.
- Hadley Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.
- Hadley Wickham, Romain François, Lionel Henry and Kirill Müller (2019). dplyr: A Grammar of Data Manipulation. R package version 0.8.0.1. https://CRAN.R-project.org/package=dplyr
- Hadley Wickham and Lionel Henry (2019). tidyr: Easily Tidy Data with 'spread()' and 'gather()' Functions. R package version 0.8.3. https://CRAN.R-project.org/package=tidyr
- Hadley Wickham and Evan Miller (2018). haven: Import and Export 'SPSS', 'Stata' and 'SAS' Files. R package version 2.0.0. https://CRAN.R-project.org/package=haven
- Yihui Xie (2016). DT: A Wrapper of the JavaScript Library 'DataTables'. R package version 0.2. https://CRAN.R-project.org/package=DT
- Yihui Xie and J.J. Allaire and Garrett Grolemund (2018). R Markdown: The Definitive Guide. Chapman and Hall/CRC. ISBN 9781138359338. URL https://bookdown.org/yihui/rmarkdown.

# References for generating the course materials

- Barret Schloerke, JJ Allaire and Barbara Borges (2018). learnr:Interactive Tutorials for R. R package version 0.9.2.1. https://CRAN.R-project.org/package=learnr
- Winston Chang, Joe Cheng, JJ Allaire, Yihui Xie and Jonathan McPherson(2019). shiny: Web Application Framework for R. R package version 1.3.2. https://CRAN.R-project.org/package=shiny


